version: "3.3"

services: 
  api:
    build: 
      context: ./api
      target: production
    container_name: nest-server
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - 8001:3000

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
  
  frontend:
    build: 
      context: ./frontend
      target: production
    env_file:
      - .env
    volumes: 
      - ./frontend:/app
      - tables:/srv/tables
    depends_on:
      - nest-server
    ports:
      - 8000:80

volumes:
  mongodata: 
  caddy_data:
  caddy_config:
