version: "3.3"

services: 
  api:
    build: 
      context: ./api
      target: production
    container_name: nest-server
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - 8001:3000

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017

volumes:
  mongodata: 
