version: "3.3"

services: 
  api:
    build: 
      context: ./api
      target: production
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - 8001:3000

  postgres:
    image: postgres:15
    env_file:
      - .env
    ports: 
      - 5432:5432
  
  frontend:
    build: 
      context: ./frontend
      target: production
    env_file:
      - .env
    volumes: 
      - ./frontend:/app
    depends_on:
      - api
    ports:
      - 8000:80

volumes:
  mongodata: 
  caddy_data:
  caddy_config:
